version: '3'
services:
  app:
    container_name: nbuctf_web
    build: .
    image: nbuctf  # 指定构建的镜像名称为 nbuctf
    ports:
      - "8889:8889"
    volumes:
      - .:/app
    depends_on:
      - redis
      - mysql
    command: ["./wait_service_create.sh", "mysql", "redis", "./main"]
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=mysql
  redis:
    image: redis:6.0.6
  mysql:
    image: mysql:8.0.21
    environment:
      - MYSQL_ROOT_PASSWORD=nbuctf#2023#dev
