system:
    env: develop # public or develop or develop-casbin（开发模式不启用casbin鉴权）
    host: 127.0.0.1
    port: 8889
    router-prefix: ""
    db-type: mysql
    use-redis: false
    use-multipoint: false
    oss-type: local #存储方式：local（本地）
jwt:
    signing-key: 4a482bfe-51fe-45cf-8274-7d8fba889a94 # 32位随机字符串，签名密钥
    expires-time: 7d
    buffer-time: 1d
    issuer: nbuctf
local:
    path: uploads/file
    store-path: uploads/file
mysql:
    prefix: ""
    port: "3306"
    config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: nbuctf
    username: root
    password: nbuctf#2023#dev
    path: 127.0.0.1
    engine: ""
    log-mode: error
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
redis:
    db: 0
    addr: 127.0.0.1:6379
    password: ""
zap:
    level: info
    prefix: '[nbuctf]'
    format: console
    director: log
    encode-level: LowercaseColorLevelEncoder
    stacktrace-key: stacktrace
    max-age: 0
    show-line: true
    log-in-console: true

captcha:
    key-long: 6
    img-width: 240
    img-height: 80
    open-captcha: 3 #3次登录失败后需要验证码，0则每次都需要
    open-captcha-timeout: 3600